### ISSUE TITLE
building on windows

### ISSUE THREAD

**Issue by GamerXD8991** [leaty/rkeep#3]
Trying to build on windows with x86_64-pc-windows-msvc causes 2 errors.
first there is a problem with git_version(). this could be something related to my git installation (github desktop) 
and secondly there are Unix io calls which can't be accessed on windows (for obvious reasons).

sadly I don't have any Rust expierence so I can't fix the second error without getting into a completly new language

**Comment by GamerXD8991** [comment]
ok, thanks non the less for informing me :)

**Comment by leaty** [comment]
No problem, if you want to you could just join the light of linux :smile: 

That's unless you have to play games with invasive kernel anticheats, almost all other games work (sometimes faster even).
