### ISSUE TITLE
Case sensitive search

### ISSUE THREAD

**Issue by chrisbergs** [leaty/rkeep#7]
When searching for name. It's now case sensitive. Maybe setable in config?

**Comment by leaty** [comment]
It's currently non-configurable, but it should be easy to add.

**Comment by leaty** [comment]
I see two options, either add a config option for this and simply add `-i` to: https://github.com/leaty/rkeep/blob/21899f74a1c62d457b5e81a7e29350d26676c0c6/src/interface/rofi.rs#L7

Or perhaps go as far as allowing completely custom commands for: https://github.com/leaty/rkeep/blob/21899f74a1c62d457b5e81a7e29350d26676c0c6/src/interface/rofi.rs#L5-L7

This would of course not be as nice *looking* in the configuration file, but on the other hand it allows for full customization, even other dmenu alternatives would work and it would no longer be locked to just rofi.

**Comment by leaty** [comment]
Fixed in https://github.com/leaty/rkeep/commit/4657689dcde8788fb443dd17377bfe2aa6004f09
